### ISSUE TITLE
How to save setting for a particular user?

### ISSUE THREAD

**Issue by ramanbuttar** [accessd/rails-settings-ui#39]
`thing_type` and `thing_id` aren't being updated. How do I pass in the context of a user when saving a setting?

**Comment by accessd** [comment]
You can try to redefine `RailsSettingsUi::SettingsController` methods like this:

```
  def update_all
    if @errors.any?
      render :index
    else
      coerced_values.each { |name, value| current_user.settings[name] = value }
      redirect_to [:settings]
    end
  end

  private

  def collection
    all_settings = default_settings.merge(current_user.settings.public_send(get_collection_method))
    all_settings_without_ignored = all_settings.reject{ |name, description| RailsSettingsUi.ignored_settings.include?(name.to_sym) }
    @settings = Hash[all_settings_without_ignored]
    @errors = {}
  end
```

So, here it is we've replaced `RailsSettingsUi.settings_klass` to `current_user.settings`

**Comment by ramanbuttar** [comment]
What would you recommend to make this configurable?

**Comment by accessd** [comment]
We have option `settings_class` in config. It could be lambda, like: `->() { current_user.settings }`. And in controller then: `coerced_values.each { |name, value| RailsSettingsUi.settings_klass.call[name] = value }`

Also there's `RailsSettingsUi.settings_klass.defaults` in `RailsSettingsUi::SettingsHelper`. Probably it should be removed, because settings for user don't have default values.

**Comment by ramanbuttar** [comment]
Posted #41 . Have a look.
